-- Add new column types: NUMBER, DATE, PERSON, PRIORITY
ALTER TYPE "ColumnType" ADD VALUE IF NOT EXISTS 'NUMBER';
ALTER TYPE "ColumnType" ADD VALUE IF NOT EXISTS 'DATE';
ALTER TYPE "ColumnType" ADD VALUE IF NOT EXISTS 'PERSON';
ALTER TYPE "ColumnType" ADD VALUE IF NOT EXISTS 'PRIORITY';
